# This is a basic workflow to help you get started with Actions

name: check

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    path: 
      - '**/*.csv'
      - '**/*.gui'
    branches: [ master ]
  pull_request:
    path: 
      - '**/*.csv'
      - '**/*.gui'
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Check encoding
        run: |
          for file in *.{gui,gfx}; do
            if ! iconv -f WINDOWS-1252 -t UTF-8 $file >/dev/null; then
              echo "All text files must be in WINDOWS-1252 encoding." >&1
              echo "Errors found in reading $file" >&1
              exit 1
            fi
          done
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          cd .github/workflows
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Python
        run: |
          cd gfx/interface/
          ../../.github/workflows/check-dds.py
